#development:
#  adapter: sqlite3
#  database: db/development.sqlite3

development:
  adapter: mysql2
  database: grape
  username: root
  password: 19930901
  encoding: utf8
  pool: 5
  host: localhost

production:
  adapter: mysql2
  database: grape
  username: root
  password: 19930901
  encoding: utf8
  pool: 5
  host: localhost